### ISSUE TITLE
Merge with ahmetoner/whisper-asr-webservice

### ISSUE THREAD

**Issue by ayancey** [chinaboard/whisperX-service#1]
Hi,

There is a [pull request](https://github.com/ahmetoner/whisper-asr-webservice/pull/125) open to add WhisperX to the original ahmetoner/whisper-asr-webservice repo. Would you consider working with them to add WhisperX to the project?

**Comment by chinaboard** [comment]
hi @ayancey openai-whisper, faster-whisper and whisperX have different response structures. I don't think a simple merge all in one is good idea.

**Comment by ayancey** [comment]
Yeah it’s difficult. The goal of the service is to offer a normalized format. There is some standardization like SRT format

**Comment by ayancey** [comment]
Closing this but maybe some collaboration can be done on standardizing a JSON format, specifically with dealing with the differences between whisper/whisperX/faster-whisper: https://github.com/ahmetoner/whisper-asr-webservice/pull/125

Thanks!
